CREATE TABLE USUARIO (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR ( 50 ) UNIQUE NOT NULL,
	PASSWORD VARCHAR ( 50 ) NOT NULL,
	EMAIL VARCHAR ( 255 ) UNIQUE NOT NULL
)

CREATE TABLE COLUNA (
	ID SERIAL PRIMARY KEY,
	ID_NOME VARCHAR ( 50 ) UNIQUE NOT NULL,
	DESCRICAO VARCHAR ( 255 ) NOT NULL
)

CREATE TABLE CHAMADO (
	ID SERIAL PRIMARY KEY,
	TITULO VARCHAR ( 100 ) NOT NULL,
	DESCRICAO VARCHAR(255),
	ID_USUARIO INTEGER,
	TIPO_PROTOCOLO VARCHAR(1) NOT NULL,
	STATUS INTEGER NOT NULL	
)

INSERT INTO COLUNA (ID_NOME, DESCRICAO) VALUES 
('caixa_entrada','Caixa de Entrada'),
('execucao','Em Execução'),
('aprovacao','Em aprovação'),
('aguardando_versao','Aguardando versão')